#!/bin/bash

file1="file1.txt"
file2="file2.txt"

if cmp -s "$file1" "$file2"
then
    echo "Files are identical. Deleting $file2..."
    rm "$file2"
else
    echo "Files are different. No deletion."
fi

